[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = stlink
; board_upload.offset_address = 0x8000800 ; Xóa bỏ offset vì nạp thẳng bằng ST-Link
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON

