[platformio]
src_dir = .
include_dir = .

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
upload_command = st-flash --reset write $SOURCE 0x8000000
build_src_filter = +<*.cpp> +<*.ino> -<.git/> -<.pio/>
build_flags = 
	-D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	-D USBCON
